# Generated by Django 4.2.1 on 2023-05-14 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardsTextStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_1', models.IntegerField(choices=[(0, 'WRONG'), (1, 'Correct but difficult'), (2, 'CORRECT')])),
                ('date_1', models.DateTimeField(auto_now=True)),
                ('result_2', models.IntegerField(choices=[(0, 'WRONG'), (1, 'Correct but difficult'), (2, 'CORRECT')], null=True)),
                ('date_2', models.DateTimeField(null=True)),
                ('result_3', models.IntegerField(choices=[(0, 'WRONG'), (1, 'Correct but difficult'), (2, 'CORRECT')], null=True)),
                ('date_3', models.DateTimeField(null=True)),
                ('flash_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_app.questiontext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
