# Generated by Django 4.2.1 on 2023-05-20 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flash_app', '0002_flashcardstextstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardstextstatus',
            old_name='date_1',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='flashcardstextstatus',
            old_name='result_2',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='flashcardstextstatus',
            name='date_2',
        ),
        migrations.RemoveField(
            model_name='flashcardstextstatus',
            name='date_3',
        ),
        migrations.RemoveField(
            model_name='flashcardstextstatus',
            name='result_1',
        ),
        migrations.RemoveField(
            model_name='flashcardstextstatus',
            name='result_3',
        ),
        migrations.RemoveField(
            model_name='flashcardstextstatus',
            name='user',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('amount_of_cards', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_app.category')),
                ('flash_cards', models.ManyToManyField(through='flash_app.FlashCardsTextStatus', to='flash_app.questiontext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flashcardstextstatus',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flash_app.session'),
        ),
    ]
